# Generated by Django 4.2.9 on 2024-01-09 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='competence__name_84d051_idx')],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('competence_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_group', to='competence.group')),
            ],
            options={
                'ordering': ['competence_group__name', 'name'],
                'indexes': [models.Index(fields=['name'], name='competence__name_1afed5_idx'), models.Index(fields=['competence_group', 'name'], name='competence__compete_da8df7_idx')],
            },
        ),
    ]
