# Generated by Django 4.2.9 on 2024-01-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0001_initial'),
        ('account', '0005_alter_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='project_competence_joined', to='competence.competence'),
        ),
    ]
