# Generated by Django 4.2.9 on 2024-01-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_project_competences'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='projects', to='account.employee'),
        ),
    ]
