# Generated by Django 5.0.6 on 2024-05-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_employee_belbin_test_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="selected_employees",
            field=models.ManyToManyField(
                blank=True, related_name="selected_projects", to="account.employee"
            ),
        ),
    ]
